language: go
arch:
  - AMD64
  - ppc64le
go:
  - "1.14.x"
  - "1.15.x"
script:
  - GOOS=windows go install github.com/chzyer/readline/example/...
  - GOOS=linux go install github.com/chzyer/readline/example/...
  - GOOS=darwin go install github.com/chzyer/readline/example/...
  - go test -race -v
